from typing import Protocol, Optional
from app.domain.models import Document, DocumentChunk, Report, SyncSummary, SearchResult


class EmbeddingProvider(Protocol):
    def embed_texts(self, texts: list[str]) -> list[list[float]]: ...
    def embed(self, text: str) -> list[float]: ...


class LLMProvider(Protocol):
    def generate(self, prompt: str) -> str: ...


class VectorStore(Protocol):
    def upsert(
        self,
        ids: list[str],
        embeddings: list[list[float]],
        documents: list[str],
        metadatas: list[dict],
    ) -> None: ...

    def search(
        self,
        embedding: list[float],
        n_results: int = 10,
    ) -> list[dict]: ...

    def delete_by_document_id(self, document_id: int) -> None: ...

    def delete_all(self) -> None: ...


class DocumentRepositoryPort(Protocol):
    def upsert(self, doc: dict) -> int: ...
    def get_all_meta(self) -> dict[str, dict]: ...
    def get_by_page_id(self, page_id: str) -> Optional[dict]: ...
    def mark_deleted(self, page_id: str) -> None: ...
    def count(self) -> int: ...
    def search_by_keyword(self, keyword: str, limit: int = 20) -> list[dict]: ...


class ChunkRepositoryPort(Protocol):
    def replace_chunks(self, document_id: int, chunks: list[dict]) -> list[int]: ...
    def get_by_document_id(self, document_id: int) -> list[dict]: ...


class ReportRepositoryPort(Protocol):
    def save(self, report: dict) -> int: ...
    def get_by_type(self, report_type: str) -> list[dict]: ...
    def get_by_period_key(self, period_key: str) -> Optional[dict]: ...


class SyncHistoryRepositoryPort(Protocol):
    def create(self, sync_type: str) -> int: ...
    def finish(self, sync_id: int, status: str, result: dict) -> None: ...
    def get_last(self) -> Optional[dict]: ...
